/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Function.DataCalon;
import Function.DatabaseConnection;
import Function.ListArray;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mtauf
 */
public class Calon extends javax.swing.JFrame {
    private int i=-1,jumlah;
    private String nim=null,nimMahasiswa=null;
    DatabaseConnection datacon = new DatabaseConnection();
    ListArray listArray=new ListArray();
    ArrayList<DataCalon> list = new ArrayList<>();
    private char privilage;
    Timer timer;
    int countTimer=60;
    /**
     * Creates new form Voter
     */
    AdminPanel adminPanel;
    public Calon() {
        initComponents();
        ShowData("SELECT * FROM calon");
    }

    public Calon(char privilage, String nimMahasiswa, AdminPanel adminPanel){
        initComponents();
        this.setResizable(false);
        this.privilage=privilage;
        this.nimMahasiswa=nimMahasiswa;
        
        if(privilage=='a'){
            jButton2_Vote.setVisible(false);
            this.adminPanel=adminPanel;
            labelTimer.setVisible(false);
        }else if(privilage=='v'){
            jButton1_Add.setVisible(false);
            jButton3_Edit.setVisible(false);
            jButton5_Remove.setVisible(false);
            labelTimer.setVisible(true);
            timerOn();            
        }
        ShowData("SELECT * FROM calon");        
    }
    void timerOn(){
        timer = new Timer(1000, new ActionListener() {
           
            @Override
            public void actionPerformed(ActionEvent ae) {
                countTimer--;
                labelTimer.setText(Integer.toString(countTimer));
                if(countTimer==0){
                    
                    Connection con = datacon.getConnection();
                    Statement st=null;
                    try{
                        st=con.createStatement();
                        if(st.executeUpdate("UPDATE mahasiswa set keterangan=1 WHERE NIM='"+nimMahasiswa+"'")==1){
                            if(st.executeUpdate("DELETE from loginvoter where username='"+nimMahasiswa+"'")==1 ){
                                dispose();
                                JOptionPane.showMessageDialog(null, "Anda golput!");
                                LoginForm login = new LoginForm();
                                login.setVisible(true);
                                login.setLocationRelativeTo(null);
                        }
                    }
                    }catch(SQLException e){
                        e.printStackTrace();
                    }
                    timer.stop();
                }
            }
        });
       timer.start();
    }
    public void ShowData(String query){
        list = listArray.getListDataCalon(query);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        System.out.println("Load!");
        model.setRowCount(0);
        Object[] row=new Object[3];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getNim();
            row[1]=list.get(i).getNama();
            row[2]=list.get(i).getKeterangan();
            model.addRow(row);
        }
        int sizeData=jTable1.getRowCount();
        String temp=String.valueOf(sizeData);
        jLabel5.setText("Banyak Data: "+temp);
    }
    
    public void executeSQLQuery(String query, String message, boolean show){
        DatabaseConnection datacon = new DatabaseConnection();
        Connection con=datacon.getConnection();
        Statement st;
        try{
            st=con.createStatement();
            if((st.executeUpdate(query)) ==1){
                if(show){
                    JOptionPane.showMessageDialog(this, message+" Berhasil!");
                }
            }else{
            }
        }catch(SQLException e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed!");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String imgPath=null;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        jButton1_Add = new javax.swing.JButton();
        jButton2_Vote = new javax.swing.JButton();
        jButton3_Edit = new javax.swing.JButton();
        jButton5_Remove = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelNIM = new javax.swing.JLabel();
        labelTimer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelVisiMisi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("jLabel5");

        labelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCalon/update data calon nopic.png"))); // NOI18N

        jButton1_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCalon/add button.png"))); // NOI18N
        jButton1_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AddActionPerformed(evt);
            }
        });

        jButton2_Vote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCalon/vote button.png"))); // NOI18N
        jButton2_Vote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_VoteActionPerformed(evt);
            }
        });

        jButton3_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCalon/editbutton.png"))); // NOI18N
        jButton3_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_EditActionPerformed(evt);
            }
        });

        jButton5_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCalon/remove button.png"))); // NOI18N
        jButton5_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_RemoveActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        labelNama.setText("Name");

        labelNIM.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelNIM.setText("NIM");

        labelTimer.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelTimer.setText("Time : 60");

        labelVisiMisi.setEditable(false);
        labelVisiMisi.setColumns(20);
        labelVisiMisi.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        labelVisiMisi.setRows(5);
        jScrollPane2.setViewportView(labelVisiMisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPhoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTimer)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2_Vote, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPhoto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNama)
                                .addGap(5, 5, 5)
                                .addComponent(labelNIM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2_Vote, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ImageIcon ResizeImage (String ImagePath, byte[] pic){
        ImageIcon MyImage=null;
        if(ImagePath!=null){
            MyImage=new ImageIcon(ImagePath);
        }else{
            MyImage=new ImageIcon(pic);
        }
        Image img=MyImage.getImage();
        Image newImg=img.getScaledInstance(labelPhoto.getWidth(), labelPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        return image;
        
    }
    public String getPhotoPath(){
          String x=System.getProperty("user.dir");
          String y=x+"\\PhotoCalon";
          System.out.println(y);
          return y;
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        i=jTable1.getSelectedRow();
//      Display Photo
        list=listArray.getListDataCalon("SELECT * FROM calon");
        nim=list.get(i).getNim().toString();
        
//      Display NIM NAMA VISI
        jumlah=list.get(i).getDipilih();
        labelNama.setText(list.get(i).getNama().toString());
        labelNIM.setText(list.get(i).getNim().toString());
        labelVisiMisi.setText(list.get(i).getKeterangan().toString());
        imgPath=getPhotoPath()+"\\"+list.get(i).getNim()+".jpg";
        labelPhoto.setIcon(ResizeImage(imgPath, null));
        
        System.out.println(imgPath);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AddActionPerformed
        EditCalon add= new EditCalon(this);
        add.setVisible(true);
        this.setEnabled(false);
        add.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_AddActionPerformed

    private void jButton2_VoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_VoteActionPerformed
//      Vote 
        int choice=JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin vote calon nomor urut "+(i+1)
                +" Dengan \n "
                +"Nama: "+labelNama.getText().toString()+"\n"+
                "NIM: "+labelNIM.getText().toString()+" ?","Delete Confirmation",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            jumlah=jumlah+1;
//          tambah 1 banyak yang milih calon x
            String query=("UPDATE calon set dipilih="+jumlah+" WHERE NIM='"+nim+"'");
            Connection con = datacon.getConnection();
            try {
                Statement st = con.createStatement();
                if(st.executeUpdate(query)==1){
                    if(st.executeUpdate("UPDATE mahasiswa set keterangan=1, vote_who='"+nim+"'WHERE NIM='"+nimMahasiswa+"'")==1){
                        if(st.executeUpdate("DELETE from loginvoter where username='"+nimMahasiswa+"'")==1 ){
                            JOptionPane.showMessageDialog(this, "SUKSES!");
                            dispose();
                            LoginForm login = new LoginForm();
                            login.setVisible(true);
                            login.setLocationRelativeTo(null);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Calon.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "FAILED!");
            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_VoteActionPerformed

    private void jButton5_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_RemoveActionPerformed
        String nim=jTable1.getValueAt(i, 0).toString();
        int choice=JOptionPane.showConfirmDialog(this, "Ingin menghapus data Calon dengan NIM:"+nim+" ?","Delete Confirmation",JOptionPane.YES_NO_OPTION);
        if(choice==JOptionPane.YES_OPTION){
            executeSQLQuery("UPDATE mahasiswa set keterangan=0 where vote_who='"+nim+"'", "", false);
            executeSQLQuery("DELETE FROM calon WHERE NIM='"+nim+"'", "DELETE", true);
            ShowData("SELECT * FROM calon");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5_RemoveActionPerformed

    private void jButton3_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_EditActionPerformed
        i=jTable1.getSelectedRow();
        String nim=jTable1.getValueAt(i, 0).toString();
        String nama=jTable1.getValueAt(i, 1).toString();
        String keterangan=jTable1.getValueAt(i, 2).toString();
        new EditCalon(this, nim, nama, keterangan, imgPath).setVisible(true);
        this.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_EditActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(privilage=='a'){
            dispose();
            adminPanel.setEnabled(true);
        }else{
            Connection con = datacon.getConnection();
            Statement st=null;
            try{
                st=con.createStatement();
                if(st.executeUpdate("UPDATE mahasiswa set keterangan=1 WHERE NIM='"+nimMahasiswa+"'")==1){
                    if(st.executeUpdate("DELETE from loginvoter where username='"+nimMahasiswa+"'")==1 ){
                        dispose();
                        JOptionPane.showMessageDialog(null, "Anda golput!");
                        LoginForm login = new LoginForm();
                        login.setVisible(true);
                        login.setLocationRelativeTo(null);
                    }
                }
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calon().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Add;
    private javax.swing.JButton jButton2_Vote;
    private javax.swing.JButton jButton3_Edit;
    private javax.swing.JButton jButton5_Remove;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JTextArea labelVisiMisi;
    // End of variables declaration//GEN-END:variables
}
